version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "5010:5010"
    environment:
      DB_CONN: "redis://127.0.0.1:6379/0"
    restart: always
    network_mode: host