version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "5010:5010"
    environment:
      DB_CONN: "redis://172.17.0.2:6379/0"
    restart: always
    network_mode: bridge